DATA_IS_3D: False
TRAINING_IS_2D: True

DATASET:
  NAME: 'Fundus'

TRAIN:
  CHECKPOINT_FREQ: 50

MODEL:
  NAME: 'medseg_diff'
  SPATIAL_DIMS: 2
  PATCH_SIZE: [384, 384]
  IN_CHANNELS: 3
  OUT_CHANNELS: 3
  EMBED_CHANNEL: 32
  FEATURES: [32, 32, 64, 64, 128, 128, 256]
  STRIDES: [2, 2, 2, 2, 2, 2]
  DROPOUT: 0.
  NORM: 'BATCH'
  TIME_STEPS: 100
  DIFFUSION:
    LOSS: 'l1'

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 8
  TEST:
    BATCH_SIZE: 8
  NUM_WORKERS: 8

OPTIM:
  NAME: 'adamw'
  LR: 0.0001
  MAX_EPOCH: 1000
  LR_SCHEDULER: 'cosine'
