DATA_IS_3D: False
TRAINING_IS_2D: True

DATASET:
  NAME: 'Fundus'
  AUGMENT: 'nnunet_augmentation'

MODEL:
  NAME: 'resunet34_nopretrain'
  SPATIAL_DIMS: 2
  PATCH_SIZE: [384, 384]
  IN_CHANNELS: 3
  OUT_CHANNELS: 3
  NORM: 'BATCH'

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 8
  TEST:
    BATCH_SIZE: 8
  NUM_WORKERS: 8

OPTIM:
  NAME: 'sgd'
  LR: 0.01
  MAX_EPOCH: 200
  LR_SCHEDULER: 'cosine'