DATA_IS_3D: False
TRAINING_IS_2D: True

DATASET:
  NAME: 'Fundus'
  KEYS: ['data', 'region', 'seg']
  AUGMENT: 'nnunet_augmentation'

MODEL:
  NAME: 'resunet34'
  SPATIAL_DIMS: 2
  PATCH_SIZE: [384, 384]
  IN_CHANNELS: 3
  OUT_CHANNELS: 3
  NORM: 'BATCH'
  ADVER_MODEL_NAME: 'adver_hist'
  ADVER_RATE: 0.1
  ADVER_HIST:
    DATA_MIN: -1.
    DATA_MAX: 1.
    CONTROL_POINT: 11
    PROB: 0.5
    GRAD_NORM: 10.
    NUM_REGION: 20
    SELECT_REGION: 5


DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 8
  TEST:
    BATCH_SIZE: 8
  NUM_WORKERS: 8

OPTIM:
  NAME: 'sgd'
  LR: 0.01
  MAX_EPOCH: 200
  LR_SCHEDULER: 'cosine'