DATASET:
  NAME: 'Fundus'

MODEL:
  NAME: 'monaiunet'
  SPATIAL_DIMS: 2
  IN_CHANNELS: 3
  OUT_CHANNELS: 3
  FEATURES: [32, 32, 64, 64, 128, 128, 256]
  STRIDES: [2, 2, 2, 2, 2, 2]
  DROPOUT: 0.3

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 32
  NUM_WORKERS: 8

OPTIM:
  NAME: 'sgd'
  LR: 0.01
  MAX_EPOCH: 1000
  LR_SCHEDULER: 'cosine'